before_install:
- openssl aes-256-cbc -K $encrypted_13c4689d1169_key -iv $encrypted_13c4689d1169_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install: true
script: true
addons:
  ssh_known_hosts:
  - buttplug.world
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet index.html buttplugworld@buttplug.world:/home/buttplugworld/beta.buttplug.world
  on:
    branch: master
