before_deploy:
- openssl aes-256-cbc -K $encrypted_13c4689d1169_key -iv $encrypted_13c4689d1169_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install: true
script: true
addons:
  ssh_known_hosts:
  - buttplug.world
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet index.html .htaccess buttplugworld@buttplug.world:/home/buttplugworld/buttplug.world
  on:
    branch: release
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet index.html .htaccess buttplugworld@buttplug.world:/home/buttplugworld/beta.buttplug.world
  on:
    branch: beta
